# Numpy Assigment

 1. Import the numpy package under the name `np`and version and the configuration .


In [4]:
import numpy as np
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/ProgramData/anaconda3/Library/include
    lib directory: C:/ProgramData/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
  

2.Create a 1D array of numbers from 0 to 9

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3.Create a 3×3 numpy array of all True’s


In [6]:
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

3.Extract all odd numbers from array

In [9]:
x=np.arange(1,21)
x[x%2==1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4.Replace all odd numbers in array with -1

In [12]:
x[x%2==1]=-1
print(x)

[-1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1 20]


5.Replace all odd numbers in array with -1 without changing arr

In [21]:
arr=np.arange(1,15)

print(arr)
x=arr.copy()
x[x%2==1]=-1
x

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14])

6.Convert a 1D array to a 2D array with 2 rows

In [25]:
arr1=np.arange(1,7).reshape(2,3)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

7.Stack arrays a and b vertically

In [12]:
import numpy as np
a= np.arange(1,7).reshape(2,3)
print(a)
b=np.arange(8,14).reshape(2,3)
print(b)
result= np.vstack((a,b))
print(result)

[[1 2 3]
 [4 5 6]]
[[ 8  9 10]
 [11 12 13]]
[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]
 [11 12 13]]


8. How to stack two arrays horizontally?

In [14]:
result=np.hstack((a,b))
result

array([[ 1,  2,  3,  8,  9, 10],
       [ 4,  5,  6, 11, 12, 13]])

9.Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
Input: a = np.array([1,2,3])
Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2,3])

In [17]:
a=[1,2,3]
np.hstack((np.repeat(a, 3), np.tile(a, 3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

10. How to get the common items between two python numpy arrays?

In [31]:
a=np.arange(1,6)
b=np.arange(3,9)
print(a)
print(b)
x=np.intersect1d(a,b)
x

[1 2 3 4 5]
[3 4 5 6 7 8]


array([3, 4, 5])

11.How to remove from one array those items that exist in another?

In [34]:
np.setdiff1d(b,a)

array([6, 7, 8])

12. How to compute the mean, median, standard deviation of a numpy array?

In [53]:
a=np.arange(0,20).reshape(5,4)
a
x=np.mean(a)
x
y=np.median(a)
y
z=np.std(a)
z

5.766281297335398

13.How to convert an array of arrays into a flat 1d array?

In [70]:
a1= np.arange(1,4)
a2= np.arange(5,9)
a3=np.concatenate([a1,a2])
a3


array([1, 2, 3, 5, 6, 7, 8])

14. Iterate over nd array

In [71]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [73]:
for a in np.nditer(a,order='c'):
    print(a)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [83]:
b= np.arange(0,15).reshape(3,5)
print(b)
for b in np.nditer(b,order='F'):
    print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
0
5
10
1
6
11
2
7
12
3
8
13
4
9
14
