# Numpy Assigment

 1. Import the numpy package under the name `np`and version and the configuration .


In [4]:
import numpy as np
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/ProgramData/anaconda3/Library/include
    lib directory: C:/ProgramData/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
  

2.Create a 1D array of numbers from 0 to 9

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3.Create a 3×3 numpy array of all True’s


In [6]:
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

3.Extract all odd numbers from array

In [9]:
x=np.arange(1,21)
x[x%2==1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4.Replace all odd numbers in array with -1

In [12]:
x[x%2==1]=-1
print(x)

[-1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1 20]


5.Replace all odd numbers in array with -1 without changing arr

In [21]:
arr=np.arange(1,15)

print(arr)
x=arr.copy()
x[x%2==1]=-1
x

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14])

6.Convert a 1D array to a 2D array with 2 rows

In [25]:
arr1=np.arange(1,7).reshape(2,3)
arr1

array([[1, 2, 3],
       [4, 5, 6]])